name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'

      - name: Build
        run: go build -v ./...

  docker-login:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4  # Add this step to access the code

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    runs-on: ubuntu-latest
    needs: docker-login
    steps:
      - uses: actions/checkout@v4  # Add this step to access the code

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/task-tracker:latest .

  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/task-tracker:latest
