name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

  setup-go:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'

  build:
    runs-on: ubuntu-latest
    needs: setup-go
    steps:
    - name: Build
      run: go build -v ./...

  docker-login:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    runs-on: ubuntu-latest
    needs: docker-login
    steps:
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/task-tracker:latest .

  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/task-tracker:latest
